### ISSUE TITLE
Can't switch language tabs if blocking trackers

### ISSUE THREAD

**Issue by sammachin** [Nexmo/nexmo-developer#1288] opened 2018-12-10 11:05 UTC
If using firefox's default tracker blocking then I can't switch tabs on the application code samples https://developer.nexmo.com/api/application#462542cdaab85ab543999bfe01d3aa76

I think this _might_ be related to segment.io which is blocked as a tracker?

Seems to work fine on the voice building blocks though
also works fine in chrome
or if I disable tracker protection for the site

**Comment by mheap** [comment] 2018-12-11 13:16
I can't seem to reproduce even with the strictest settings.

![screen shot 2018-12-11 at 13 16 00](https://user-images.githubusercontent.com/59130/49803152-f41ed700-fd46-11e8-91fd-c962b462310f.png)

The tabs on that page are working fine for me. Can you reproduce it reliably?

**Comment by mheap** [comment] 2018-12-11 17:52
I've caught up with Sam and we can't reproduce. It's happened on occasion but a refresh fixed it. We've tested locally, on production and on a review app. Closing until we can reproduce

**Closed by mheap** 2018-12-11 17:52 UTC
