### ISSUE TITLE
Ruby syntax highlighting not working in Mobile App Invites tutorial

### ISSUE THREAD

**Issue by tommorris** [Nexmo/nexmo-developer#594] opened 2018-03-05 16:58 UTC
## Description

Some strange code seems to be appearing in a Ruby code sample in the [Mobile App Invites](https://developer.nexmo.com/tutorials/mobile-app-invites) tutorial.

## What should happen?

It should highlight the Ruby syntax correctly. Here's how Vim highlights it on my local machine.

![screen shot 2018-03-05 at 16 57 52](https://user-images.githubusercontent.com/175/36988293-74059bae-2096-11e8-9691-5df2a4eff8e2.png)

## What actually happened?

![screen shot 2018-03-05 at 16 56 06](https://user-images.githubusercontent.com/175/36988221-4854ea28-2096-11e8-9d90-cc8c0fb2c857.png)

**Comment by tommorris** [comment] 2018-03-05 17:01
A similar issue is happening with this JS code sample in [Private Voice Communication](https://developer.nexmo.com/tutorials/private-voice-communication):

![screen shot 2018-03-05 at 17 00 30](https://user-images.githubusercontent.com/175/36988421-be2a5ecc-2096-11e8-9b59-dfc7768860f6.png)

**Comment by tommorris** [comment] 2018-03-05 17:21
And another one spotted, this time in [Fraud Scoring and Phone Number Verification](https://developer.nexmo.com/tutorials/fraud-scoring-and-phone-number-verification):

![screen shot 2018-03-05 at 17 20 53](https://user-images.githubusercontent.com/175/36989429-9f6219d2-2099-11e8-8cb9-3982af5b4a47.png)

**Comment by leggetter** [comment] 2018-03-05 18:04
Duplicate of https://github.com/Nexmo/nexmo-developer/issues/586 (although more detail)

**Comment by adambutler** [comment] 2018-03-05 21:03
All fixed by 9f377c21

**Closed by adambutler** 2018-03-05 21:03 UTC
